### ISSUE TITLE
Official new destiny server issue

### ISSUE THREAD

**Issue by BigKMacD** [Fundryi/Destiny#10]
Im not sure if this is the right place to put this but
the server is continuously closing and currently unplayable.

**Comment by Fundryi** [comment]
Yea Im aware of that problem, I took the server offline for testing etc.

**Comment by BigKMacD** [comment]
Ok. The only new things im aware of on the server is my quarry in the deep dark and a dragon farm from woot by another player.

**Comment by Fundryi** [comment]
I know the issue already, I cant fix it without the person who causes it.
It has something to do with his Refined Storage System, that try to access some external "Storage"

**Comment by BigKMacD** [comment]
Ok. My username is KelvinKev. DiamondDude was having crashes due to his storage.

**Comment by Fundryi** [comment]
Also to be updated always join our Discord: https://discordapp.com/invite/hxVhpcU
Server/modpack updated will be out today with fixes.
