### ISSUE TITLE
Significant lag when opening/closing inventory, easy solution

### ISSUE THREAD

**Issue by jezzen** [Fundryi/Destiny#11]
Whenever you open or close pretty much any inventory, the game freezes up for a second or so. This is caused by NEI and can be solved ingame by disabling NEI in the inventory screen. Can't say how much affect this has on a server.

Of course, this will remove the overlays but that can be solved by replacing NEI with More Overlays.

There was also a lag spike pretty frequently which would increase over time as well which I haven't narrowed down yet, but I'll see if the update has solved it for now.

**Comment by Fundryi** [comment]
Thank u for letting me know, did you also report this problem to the Mod author? So he can fix it ;)

**Comment by jezzen** [comment]
There is an issue there about memory leaks with a reference about what is basically the same thing happening in SevTech Ages
@TheCBProject/NotEnoughItems#153

Not 100% sure that's how the markup goes for referencing another project... but that's how it looks in [https://github.com/Darkosto/SevTech-Ages/issues/778](url)
