### ISSUE TITLE
Tinkers Problem.

### ISSUE THREAD

**Issue by nyphatonic** [Fundryi/Destiny#12]
I found an issue in the 4th chapter in the Questbook, Tinkering.
The Quest: Smite Need Items, that not shown in JEI. Also no Quest there for Grout, which will unlock the Smeltery Part. After hours of playing around that Pack, which is very nice, of Course, i've found These two issues. 
I hope that would be fixed or explained how to soon :)

best regrads 
Nypha

**Comment by Fundryi** [comment]
Sorry for this late response, This bug/fail is not fixed, Update will come in a few days.
Thank you for letting me know!

Also if u wanna see "ALL" items in JEI just press "Numpad 9" to disable the JEI Filter.
To fix the Quest Bug just type "/bq_admin edit" and edit/check it in the Quest after u fixed it just type "/bq_admin edit" again to disabled the admin mode. 

Regards, Fundryi
