### ISSUE TITLE
[Suggestion] Terrain Generator

### ISSUE THREAD

**Issue by begonethought** [Fundryi/Destiny#17]
You could use [Open Terrain Generator](https://minecraft.curseforge.com/projects/open-terrain-generator) with [Biome Bundle](https://minecraft.curseforge.com/projects/biome-bundle) as a Terrain Generator. You could also expand on that with your own custom trees or other objects.
There isn't _only_ Biomes 'O Plenty if you look hard enough.

**Comment by Fundryi** [comment]
Sorry for the late Respons, but OTG/Biome Bundle doesn't work well with Biomes 'O Plenty and other world generator mods, otherwise I would have already chosen them. I added a few new Terrain Generators to the new updated, they should be all good enough ;)
