### ISSUE TITLE
[Suggestion] Remove clientside mods in server package

### ISSUE THREAD

**Issue by mrdeadlocked** [Fundryi/Destiny#4]
Disabling mod clienttweaks it is client side only.
Disabling mod controlling it is client side only.
Disabling mod ctgui it is client side only.
Disabling mod ctm it is client side only.
Disabling mod custombackgrounds it is client side only.
Disabling mod custommainmenu it is client side only.
Disabling mod defaultoptions it is client side only.
Disabling mod presets it is client side only.
Disabling mod gogskybox it is client side only.
Disabling mod jeiintegration it is client side only.
Disabling mod jeresources it is client side only.
Disabling mod moreoverlays it is client side only.
Disabling mod mousetweaks it is client side only.
Disabling mod neat it is client side only.
Disabling mod reauth it is client side only.
Disabling mod resourceloader it is client side only
Disabling mod toastcontrol it is client side only.
Disabling mod wailaharvestability it is client side only.

These mods are in server package and unneeded.

**Comment by Fundryi** [comment]
I could do that but It would make me more work and it's not needed. I would always have to remove them if I made an (big) Updated for the Server version...
